### ISSUE TITLE
Ogarnięcie layoutu i stringów

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/Straciatella#112]
W plikach:
- `presentation/models/lesson_data/lesson_data_desc/lesson_data_desc_schedule.dart`
- `presentation/models/lesson_data/lesson_data_tile/lesson_data_card.dart`\
są pozostawione w sumie 3 TODO, które odpowiadając za te długie stringi na screnach niżej
Jest jeszcze tytuł planu zajęć, więc można zrobić dwa widgety: dla planu zajęć Lecturer oraz StudyProgram zależnie jakiego typu jest obiekt planu zajęć

Oczywiście też trzeba naprawić layout by był scrollowalny na tym bottom sheetcie

![image](https://github.com/SilverNETGroupSGGW/Straciatella/assets/19827704/e2fc5524-b243-406f-8081-018140886a43)
![image](https://github.com/SilverNETGroupSGGW/Straciatella/assets/19827704/e1aa51bd-0d47-4e8c-8cad-05e3c12af3be)

**Comment by matyjb** [comment]
Fajnie to wygląda!
Dodaj tylko jeszcze 
- ładne info z jakiego studyprogramu pochodzi dany lesson by np prowadzący wiedział z kim ma zajęcia `lesson_data_card.dart linia 84`
- Dodaj ładny tytuł planu zajęć w appbarze `schedule_events_app_bar.dart linia 33` zależnie jakim planem jest (możesz scastować odpowiednio do typu LecturerExt czy StudyProgramExt `scheduleEventsCubit.state.schedule` i powyciągać w ten sposób dane

Zrób `git pull` bo dodałem switcha by zmieniło mode widoku planu zależnie od tego jakiego typu schedule wyświetlamy (lecturer'a czy studenta)

**Comment by ThePhaseless** [comment]
@matyjb resolved?
