### ISSUE TITLE
Ekran gdy nie ma wybranego planu

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/Straciatella#127]
Pierwszy ekran ten z napisem, że nie ma wybranego jeszcze żadnego z ulubionych planów (i jak user nie ma żadnych też dodanych to niech będzie tekst też o tym by sobie stworzył)

Zrobić go ładnego

**Comment by mpygruu** [comment]
Propozycja:

![Screenshot 2024-11-09 at 21 14 52](https://github.com/user-attachments/assets/cd1f21eb-0a39-4748-abd4-6a050ec59e47)

**Comment by matyjb** [comment]
Kolorek od lecturera taki nie zbyt. Nasycony kolor zachęca do kliknięcia, zaś szary odradza, a przecież tu nie ma różnicy co wybierze user.

Ja bym to do jednego rzędu wsadził i coś w stylu "jestem studentem | jestem nauczycielem" plus dwie ikonki. I by nie było zbyt dużo ikonek to no tą główną bym wywalił. ALBO, ale to już marzenie, użyć flutter_animate i przejść z tego ekranu z dłonią, która macha i po pewnym czasie (albo po kliku by skipnąć) fade in na te dwie opcje, a rączka znika

**Comment by matyjb** [comment]
ale jakąś animacje trzeba dodać bo to będzie nadal faza pierwszego wrażenia po odpaleniu apki przez usera
