### ISSUE TITLE
Rozwijany FAB do filtrowania wyświetlanych zajęć

### ISSUE THREAD

**Issue by mpygruu** [SilverNETGroupSGGW/Straciatella#131]
Zaimplementować rozwijany FAB, który będzie odpowiedzialny za filtrowanie widoku na podstawie mapy byStudentGroups w klasie ScheduleFiltersInfo. Narazie bez funkcjonalności filtrowania, niech tylko prezentuje dane o semestrach i grupach z byStudentGroups po kliknięciu odpowiedniej opcji

**Comment by mpygruu** [comment]
FAB zrobiony, narazie na sztywno a nie na podstawie filtrów. Dodałem na figmie (screen poniżej) propozycję wyboru grup, semestru i planu.

Podepnę FABa do filtrów byStudentGroups jak issue 113 zostanie zmergowany.

Dodatkowo przyda się kilka ifów, żeby na przykład: 
* jeśli ktoś jest na pierwszym semestrze to nie pokazywać zmiany semestru,
* jeśli ktoś patrzy na plan wykładowcy to nie pokazywać zmiany grupy i semestru, a może w ogóle zamiast rozwijanego faba to zrobić pojedynczy, na którym jest symbol edit_calendar.

![Zrzut ekranu 2024-09-29 o 18 47 34](https://github.com/user-attachments/assets/1b89b45b-dfd3-46c1-93b7-3b8c23f6c703)

**Comment by matyjb** [comment]
Semestry lepiej przenieść do kalendarza jako takie skróty co przenoszą do pierwszego dnia danego semestru jako tagi (coś jak zazwyczaj się daje taki guzik "Dzisiaj"), bo te semestry to właśnie takie w sumie labele na osi czasu danego toku studiów. Te kółeczka z cyfrą semestru fajne, coś może da się upakować to na tym kalendarzu (jak się kliknie w aktualny dzień to się otwiera ten kalendarz, o ten mi chodzi)

![image](https://github.com/user-attachments/assets/868524f7-6962-4481-8aed-c1045826af00)

- Te rzeczy dotyczące wybierania czasu są wtedy w jednym miejscu
- Może będzie to zbyt ukryte? Ale w sumie jak user będzie się chciał cofnąć bardzo to i tak sobie odpali ten kalendarz, a tu pyk od razu przygotowane skróty do skakania do danego sema

Odnośnie pytania: Hmm, można wymusić tego faba by był zawsze widoczny albo w ustawieniach tam gdzie jest "Zarządzanie planami" będzie opcja zmiany widocznego planu (tak jak to jest w obecnej apce)

**Comment by mpygruu** [comment]
Hm, przemyślałem na świeżo, i wydaje mi się że skakanie pomiędzy semestrami to będzie event na tyle rzadki, że w sumie wystarczy przeklikanie dialogu z kalendarzykiem, bez dodatkowych przycisków. Takie przyciski byłyby bardzo fajne ale w tym przypadku skłaniałbym się do uproszczenia UI.

Myślałem o tym przycisku ze zmianą semestru też ze względu na to, że grupy studenckie się różnią między semestrami dla tego samego rocznika, ale ten problem wystarczy rozwiązać biorąc grupy dla tego semestru, do którego należy aktualnie wybrany dzień.

Jeżeli rezygnujemy z przycisku dla semestru to pozostają tylko dwa mini faby, czyli dokładnie tyle żeby rozwijalny fab nie był potrzebny 🤔 Myślałem co może się userowi przydać zamiast zmiany semestru ale na ten moment nie mam pomysłu. Jak nie wymyślimy żadnego power toola to bym też zaproponował powrót do dużego faba do zmiany planu oraz małego faba do zmiany grupy, bez rozwijania.

**Comment by mpygruu** [comment]
A co do odpowiedzi na pytanie to tak, zróbmy jak jest w obecnej apce. Jak ktoś wyłącza FAB to akceptuje konsekwencje. xD

**Comment by matyjb** [comment]
@mpygruu ScheduleFiltersCubit is done. Możesz zacząć pracować
