### ISSUE TITLE
Fake dane

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/Straciatella#140]
W FakeSggwHubRepo ogarnąć fakeowe dane używane aktualnie w apce by były spójne i miały sens (reprezentowały jakby mały wycinek prawdziwej bazy dancyh). By można było pokazać demo działającej apki

**Comment by mpygruu** [comment]
Fake dane przygotowane, od razu się apka lepiej prezentuje. 

Podczas robienia taska zauważyłem, że LecturerExt zawiera wszystkie studyPrograms, a nie tylko takie, które go dotyczą. Zakładam, że to już warstwa logiki będzie w przyszłości odpowiedzialna za to, żeby przed wyświetleniem zajęć przefiltrować zajęcia w studyPrograms i zostawić tylko te, które dany wykładowca prowadzi. Narazie nie dodawałem kodu żeby lecturer miał tylko takie studyPrograms, w których prowadzi chociaż jedne zajęcia bo nie wiedziałem jaki mamy plan odnośnie tego ale jak coś to dodam.

**Comment by mpygruu** [comment]
Kilka screenów:

![Simulator Screenshot - iPhone 16 - 2024-11-01 at 01 14 31](https://github.com/user-attachments/assets/c0dd186c-f5d7-42ed-97c9-44178e1839e1)

![Simulator Screenshot - iPhone 16 - 2024-11-01 at 01 14 20](https://github.com/user-attachments/assets/deb5c69b-d855-4d01-bd4c-5c3b10fd63e8)

![Simulator Screenshot - iPhone 16 - 2024-11-01 at 01 14 07](https://github.com/user-attachments/assets/5bea129d-6e8a-40bc-99e4-df9e930d3cbb)

**Comment by matyjb** [comment]
> Podczas robienia taska zauważyłem, że LecturerExt zawiera wszystkie studyPrograms, a nie tylko takie, które go dotyczą. Zakładam, że to już warstwa logiki będzie w przyszłości odpowiedzialna za to, żeby przed wyświetleniem zajęć przefiltrować zajęcia w studyPrograms i zostawić tylko te, które dany wykładowca prowadzi. Narazie nie dodawałem kodu żeby lecturer miał tylko takie studyPrograms, w których prowadzi chociaż jedne zajęcia bo nie wiedziałem jaki mamy plan odnośnie tego ale jak coś to dodam.

My nic nie będziemy filtrować. LecturerExt ma odnośniki do przefiltrowanych studyprograms pod względem jego zajęć tego lecturera (to będzie szło z backendu). Jeżeli w fake danych było tam dane ot tak jakieś bez filtrowania to był szybki mock i nie sugeruj się tym w ogóle
