### ISSUE TITLE
Screen zarządzania planami

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/Straciatella#160]
Zrobić screen z wszystkimi planami zajęć jakie dodał użytkownik i połączyć go z guzikiem w ustawieniach (tym zrobionym ale nie działającym).

Screen niech wyświetla w liście 
- plany zajęć dodane do ulubionych z podstawowym info jak kierunek/rocznik etc/prowadzący wraz z datą ostatniej aktualizacji
- Dla każdego z planu dodać możliwość usunięcia go
- Dodać guziki od dodawania nowego planu
- Swipe w dół by zaktualizować plany (bez implementacji samego flow updateu, niech się tam jakiś Future.delayed mieli przez parę sekund np)

**Comment by mpygruu** [comment]
Taka propozycja:

![Screenshot 2024-12-05 at 18 21 43](https://github.com/user-attachments/assets/b04cff89-5e0a-45b7-a04f-590153c3f93e)

Można też dodać usuwanie przez swipe w lewo. Edytowania raczej nie przewidujemy bo nie ma co tu edytować

**Comment by mpygruu** [comment]
Wymuszenie update można zrobić przez swipe w dół tutaj oraz w widoku FavedScheduleScreen. Nawet nie można a trzeba koniecznie aż się prosi.

**Comment by matyjb** [comment]
Tak, swipe w dół by zaktualizować plany dobry pomysł. Dopiszę do taska.
Swipe w lewo by usunąć, to już pozostawiam do inwencji twórczej deva implementującego tego taska (w końcu napisałem by "dodać możliwość usunięcia planu"

**Comment by mpygruu** [comment]
Pytanie: czy przewidujemy pokazywanie w aplikacji szczegóły prowadzącego jak np. email, telefon, pokój, godziny konsultacji o ile to jest w bolero api, i takie tam. Bo wtedy UI się zmieni, elementy listy będą klikable

**Comment by mpygruu** [comment]
Ostatecznie zdecydowałem się na taki:

![Screenshot 2024-12-05 at 22 16 04](https://github.com/user-attachments/assets/c1918f86-9aad-4cd3-9595-20caf3449154)

Uznałem, że swipe w lewo nie będzie dla każdego intuicyjny a ten kosz czerwony nie zajmuje za dużo miejsca i jest jednoznaczny.

**Comment by mpygruu** [comment]
Jutro mogę to klepnąć w ciągu dnia / wieczorem
