### ISSUE TITLE
Screen gdy plan zajęć nie istnieje albo inny error

### ISSUE THREAD

**Issue by matyjb** [SilverNETGroupSGGW/Straciatella#81]
Zrobić ładny screen (dać ładną ikonkę, coś tam napisać, tytuł planu wyciągnąć z scheduleIndex jeżeli istnieje, dać guzik od refresha etc.) gdy jest taka sytuacja, że user wybierze jakiś plan zajęć, a ten nie istnieje albo internet wywaliło etc. Widget ScheduleEventsErrorScreen jest już gotowy, trzeba go tylko uzupełnić.

------
Zaimplementowałem cubit ScheduleEventsCubit, który przetrzymuje logikę dla wyświetlania wybranego planu zajęć (przy pomocy ScheduleKey). Zapoznaj się z nim. Logika przechodzenia do tego screena też jest zrobiona w schedule_screen.dart, więc najlepiej sobie guzik w debug screenie zrób by przejść na ten screen.

**Comment by mpygruu** [comment]
Aktualny stan poniżej, jeszcze się zastanawiam co tu więcej można dodać i jakie jeszcze przypadki rozpatrzeć inne niż brak połączenia z api i defaultowy. Jak nic nie wymyślę to w sumie gotowe.

![Simulator Screenshot - iPhone 15 - 2024-03-06 at 15 46 24](https://github.com/SilverNETGroupSGGW/Straciatella/assets/92801562/67b6df4d-ffd3-4d4e-892b-d737a2061485)

**Comment by mpygruu** [comment]
Hmm a jak to będzie z nazwą dla konkretnego planu, bo gdyby dodać w app bar jako podtytuł "Wydział Zastosowań ..., Informatyka, stacjonarne, ..." to to się nawet małym druczkiem nie zmieści a jednak dobrze by było żeby użytkownik wiedział na co patrzy

Chyba że mamy jakiś lepszy pomysł na nazywanie planów?

**Comment by matyjb** [comment]
Ze skrótami będzie problem bo ich nie wygenerujesz poprawnie. W apce planu wzim my to po prostu małą czcionką zrobiliśmy i jakoś się mieści, ale no jest problem z tym i będzie trzeba coś wymyślić.

Ewentualnie się da trzy kropki jak za długie, a na kliknięcie dać pop over'a (dymek) z pełną nazwą
